### ISSUE TITLE
Switch amount data type from int to float?

### ISSUE THREAD

**Issue by joshskidmore** [Gbox4/forx#1]
Currently, forx does't support amounts that aren't whole integers. For instance, `forx btc usd -q .12` returns `forx: error: argument -q: invalid int value: '.12'`. Changing the type from `int` to `float` on line 72 in convert.py seems to resolve the issue, but I'm unsure of repercussions. I'm more than happy to submit a PR for this as well.

**Comment by Gbox4** [comment]
Nice catch, thanks! The change you suggested worked, not any repercussions as the -q value is only used when multiplying by the exchange rate.
