### ISSUE TITLE
Various cryptocurrency return "Invalid currency"

### ISSUE THREAD

**Issue by BrodieRobertson** [Gbox4/forx#5]
Attempting to convert coins such as XMR, BNB, SAND, NEAR, KLAY, etc return "Invalid currency <NAME>." error, I have confirmed these are the names used for these coins on the Coinbase website.

Steps To Reproduce:
1. Attempt to convert failing coin - forx XMR USD

![2022-01-24_15-24](https://user-images.githubusercontent.com/30792656/150724224-b88373f6-943a-44ef-b8b0-f85ecc1316d9.png)
![2022-01-24_15-26](https://user-images.githubusercontent.com/30792656/150724311-bd2c7814-2b43-42ee-a80e-df21881bda4c.png)

It's possible this isn't an issue with your application and is instead an issue with the coinbase API. Further testing indicates that lower ranked coins past the 2nd page seem to all fail.

**Comment by Gbox4** [comment]
Yep, unfortunately, these cryptocurrencies aren't supported by the Coinbase API :(

I'll close this issue and open a new one to implement an option to use an alternative API: https://github.com/Gbox4/forx/issues/6
